### ISSUE TITLE
Disallow concurrent websocket writes

### ISSUE THREAD

**Issue by matthewmueller** [mafredri/cdp#12]
Looks like the writes to the websocket stream are happening concurrently which isn't allowed in gorilla. More info here: https://godoc.org/github.com/gorilla/websocket#hdr-Concurrency

```go
panic: concurrent write to websocket connection

goroutine 52 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc4202231d0, 0xc42018f901, 0x0, 0x0, 0x0, 0x199, 0xc420200100)
	/Users/matt/go/src/github.com/gorilla/websocket/conn.go:585 +0x57b
github.com/gorilla/websocket.(*messageWriter).Close(0xc4202231d0, 0xc420024650, 0xc420024600)
	/Users/matt/go/src/github.com/gorilla/websocket/conn.go:699 +0x60
github.com/gorilla/websocket.(*Conn).prepWrite(0xc42015adc0, 0x1, 0x12a752f, 0xc420053ea8)
	/Users/matt/go/src/github.com/gorilla/websocket/conn.go:468 +0x10c
github.com/gorilla/websocket.(*Conn).NextWriter(0xc42015adc0, 0x1, 0x40, 0x50, 0xc42013ee60, 0x0)
	/Users/matt/go/src/github.com/gorilla/websocket/conn.go:488 +0x39
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc42015adc0, 0x1409ca0, 0xc42013ee60, 0x55, 0x81)
	/Users/matt/go/src/github.com/gorilla/websocket/json.go:22 +0x49
exit status 2
FAIL	command-line-arguments	2.806s
```

FWIW, I'm not sure exactly how rpcc works yet internally, but I had to deal with this once before, solving it with a write channel and a write event loop. It looked like this, though I'd probably want to update it to use context over additional channels.

**writeLoop function:**

```go
func (w *WS) writeLoop() {
	conn := w.conn
	for {
		select {
		case outgoing := <-w.writeCh:
			err := conn.WriteJSON(outgoing.Message)
			if err != nil {
				outgoing.Response <- err
			} else {
				close(outgoing.Response)
			}
		case <-w.closedCh:
			// if we've closed end the loop
			log.Info("ending outgoing loop")
			return
		}
	}
}
```

**write function:**

```go
// Write to the websocket
func (w *WS) Write(v interface{}) error {
	errorCh := make(chan error)
	req := &writeRequest{
		Message:  v,
		Response: errorCh,
	}

	// write request
	select {
	case w.writeCh <- req:
	case <-w.closedCh:
		return ErrClosed
	}

	// ensure we wrote to the socket
	select {
	case err := <-errorCh:
		return err
	case <-w.closedCh:
		return ErrClosed
	}
}
```

**Comment by mafredri** [comment]
Hmm, it looks like `websocket.(*Conn).WriteJSON` is being called but this API is not used in `rpcc`. Are you using a custom codec for the rpcc Conn?

I'm not at a computer right now but I'll investigate later today.

**Comment by matthewmueller** [comment]
Dohhh... this was on my end. Sorry for the false alarm. I just added an (unfinished) test in rpcc and it seems to be working fine.

```go
func TestConcurrentWrites(t *testing.T) {
	srv := newTestServer(t, func(conn *websocket.Conn, req *Request) error {
		resp := Response{
			ID:     req.ID,
			Result: []byte(fmt.Sprintf("%q", "hello")),
		}
		return conn.WriteJSON(&resp)
	})
	defer srv.Close()

	wg := &sync.WaitGroup{}
	wg.Add(5)
	go invoke(t, wg, srv.conn, 1)
	go invoke(t, wg, srv.conn, 1)
	go invoke(t, wg, srv.conn, 1)
	go invoke(t, wg, srv.conn, 1)
	go invoke(t, wg, srv.conn, 1)
	wg.Wait()
}

func invoke(t *testing.T, wg *sync.WaitGroup, conn *Conn, n int) {
	defer wg.Done()
	err := Invoke(nil, "test.Hello", nil, nil, conn)
	if err != nil {
		t.Fatal(err)
	}
}
```

**Comment by mafredri** [comment]
Did you also run it with `-race`? But I'm glad if it's working as it should, no worries 😄. Let me know if you can think of something that could be done to improve the above.

**Comment by matthewmueller** [comment]
Yep, I ran it with `-race`, rpcc is solid :-D
