### ISSUE TITLE
Deadlock with cdp.Sync and incoming notification

### ISSUE THREAD

**Issue by bpot** [mafredri/cdp#90]
We are seeing what appears to be a deadlock between a `cdp.Sync` call and an incoming RPC notification. The notification handling goroutine holds `Conn.streamMu` while trying to acquire `syncMessageStore.mu` and `cdp.Sync` does the opposite.

**RPC Notification**

rpcc.(*Conn).notify - holds conn.streamMu
rpcc.(*streamClients).write - holds streamClients.mu 
rpcc.(*syncMessageStore).write - blocking on syncMessageStore.mu

**cdp.Sync**

rpcc.Sync - holds streamClient.mu for each stream
rpcc.(*syncMessageStore).subscribe - holds syncMessageStore.mu
rpcc.(*Conn).listen - blocking on conn.streamMu

**Backtraces**

```
goroutine 33 [semacquire, 917 minutes]:
sync.runtime_SemacquireMutex(0xc0007a6c84, 0x40e100)
	GOROOT/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc0007a6c80)
	GOROOT/src/sync/mutex.go:134 +0xff
github.com/mafredri/cdp/rpcc.(*syncMessageStore).write(0xc0007a6c80, 0xc000796420, 0x19, 0xc0048cf080, 0x287, 0x2c0, 0x0)
	vendor/github.com/mafredri/cdp/rpcc/stream_sync.go:75 +0x81
github.com/mafredri/cdp/rpcc.(*streamClients).write(0xc0006bc500, 0xc000796420, 0x19, 0xc0048cf080, 0x287, 0x2c0)
	vendor/github.com/mafredri/cdp/rpcc/stream.go:341 +0x115
github.com/mafredri/cdp/rpcc.(*Conn).notify(0xc000458000, 0xc000796420, 0x19, 0xc0048cf080, 0x287, 0x2c0)
	vendor/github.com/mafredri/cdp/rpcc/conn.go:427 +0xd2
github.com/mafredri/cdp/rpcc.(*Conn).recv(0xc000458000, 0xc0001305f0, 0xc0001305e0)
	vendor/github.com/mafredri/cdp/rpcc/conn.go:329 +0x12d
created by github.com/mafredri/cdp/rpcc.DialContext
	vendor/github.com/mafredri/cdp/rpcc/conn.go:182 +0x334

goroutine 485461 [semacquire, 917 minutes]:
sync.runtime_SemacquireMutex(0xc00045811c, 0x0)
	GOROOT/src/runtime/sema.go:71 +0x3d
sync.(*Mutex).Lock(0xc000458118)
	GOROOT/src/sync/mutex.go:134 +0xff
github.com/mafredri/cdp/rpcc.(*Conn).listen(0xc000458000, 0xf77ba1, 0x1e, 0x1114580, 0xc0007a6c80, 0x0, 0x0, 0x0)
	vendor/github.com/mafredri/cdp/rpcc/conn.go:436 +0x54
github.com/mafredri/cdp/rpcc.(*syncMessageStore).subscribe(0xc0007a6c80, 0xf77ba1, 0x1e, 0x1114560, 0xc0007f5f80, 0xc000458000, 0x0, 0x0, 0x0)
	vendor/github.com/mafredri/cdp/rpcc/stream_sync.go:34 +0x1f7
github.com/mafredri/cdp/rpcc.Sync(0xc018af1200, 0x4, 0x4, 0x0, 0x0)
	vendor/github.com/mafredri/cdp/rpcc/stream_sync.go:160 +0x25a
github.com/mafredri/cdp.Sync(0xc000539488, 0x4, 0x4, 0x7fa37a62f2c8, 0xc002dc07a0)
	vendor/github.com/mafredri/cdp/sync.go:42 +0x146
```

**Comment by mafredri** [comment]
Ooh, this looks like a tricky one. Thanks for the detailed report! I'll try to dig into this during the next couple of days.

**Comment by mafredri** [comment]
I managed to reproduce the issue pretty quickly, and I think I found a fix for it in https://github.com/mafredri/cdp/pull/91. I'll try to verify tomorrow that there are no adverse effects to this and that it actually catches all the edge cases.

**Comment by bpot** [comment]
@mafredri awesome! thanks

**Comment by derat** [comment]
Using d92fe56cfe764d3b2523633cc23f6525dd5fe128, I'm seeing an infrequent segfault that seems like it may be related:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5787b86fd84f] 

goroutine 855 [running]: 
github.com/mafredri/cdp/rpcc.(*syncMessageStore).load(0xc0002ca820) 
	/build/eve-arcnext/usr/lib/gopath/src/ github.com/mafredri/cdp/rpcc/stream_sync.go:102   +0xaf 
github.com/mafredri/cdp/rpcc.(*syncMessageStore).load-fm() 
	/build/eve-arcnext/usr/lib/gopath/src/ github.com/mafredri/cdp/rpcc/stream_sync.go:78   +0x2c 
github.com/mafredri/cdp/rpcc.(*streamClient).write.func1() 
	/build/eve-arcnext/usr/lib/gopath/src/ github.com/mafredri/cdp/rpcc/stream.go:262   +0xa4 
github.com/mafredri/cdp/rpcc.(*streamClient).recv(0xc000297200  ,   0xc0003edc80, 0x789e407e2000, 0x0) 
	/build/eve-arcnext/usr/lib/gopath/src/ github.com/mafredri/cdp/rpcc/stream.go:229   +0x11e 
github.com/mafredri/cdp/rpcc.(*streamClient).RecvMsg(0xc000297200  ,   0x5787b8d57900, 0xc0003648a0, 0xc000297230, 0xc00016dd68) 
	/build/eve-arcnext/usr/lib/gopath/src/ github.com/mafredri/cdp/rpcc/stream.go:187   +0x34 
github.com/mafredri/cdp/protocol/target.(*receivedMessageFromTargetClient).Recv(0xc0002a4280  ,   0xc00016ddd4, 0x3, 0x2) 
	/build/eve-arcnext/usr/lib/gopath/src/ github.com/mafredri/cdp/protocol/target/domain.go:306   +0x64 
github.com/mafredri/cdp/session.(*Manager).watch(0xc000074540  ,   0xc0002e4460, 0xc0000829c0, 0xc0004bacc0, 0xc0004baba0) 
	/build/eve-arcnext/usr/lib/gopath/src/ github.com/mafredri/cdp/session/manager.go:121   +0x2d2 
created by  github.com/mafredri/cdp/session.NewManager 
	/build/eve-arcnext/usr/lib/gopath/src/ github.com/mafredri/cdp/session/manager.go:186   +0x196) (status 5) 
```

I suspect that the missing-writer check that #91 adds to rpcc/stream_sync.go will address this. Does that seem correct, or should I file a new issue?

(And thanks for this wonderful package!)

**Comment by mafredri** [comment]
@derat thanks for reporting! I believe your suspicion is correct. It looks like the same issue i uncovered while working on this one. If I've understood the issue correctly, it's related to a race between closing a Stream that has been Sync:ed and a notification (on Conn) arriving right before the syncMessageStore has unsubscribed but it is written or loaded (syncMessageStore.write/load) after the writer has been removed.

It should be mostly addressed in #91. I think there's still a tiny possibility of race which I'm still investigating how best to solve. I just pushed ab53eecb33dce8bcc1617c0edca6a882b01cc064 but with that, my hunch is that two calls to `syncMessageStore.load` could be active at the same time, which in turn interferes with the guarantees that Sync is supposed to provide.

I might do a small refactor instead of trying to plug holes, please bare with me 😄.

**Comment by derat** [comment]
No worries. Thanks for the quick reply (and fix)!

**Comment by mafredri** [comment]
@bpot @derat I believe I've addressed the edge cases in #91 now, if you have a chance to try it out that would be great! But I'll do a new release pretty soon if you wish to wait.

**Comment by derat** [comment]
@mafredri Thank you! I've patched #91 in locally and haven't noticed any issues yet.

**Comment by mafredri** [comment]
Great, thanks for testing @derat!

Release is out => [v0.22.0](https://github.com/mafredri/cdp/releases/tag/v0.22.0).
